import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {

  title: "",
  description: "Generated by create next app",
};
import Head from 'next/head';
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script src="http://localhost:3000"></script>
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon.png" />
        <title className="notranslate">HOME TEACHERS</title>
        <meta name="description" content="Web site created..." />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ` }
      >
        {children}
      </body>
    </html>
  );
}
